# Generated by Django 2.2.10 on 2021-03-11 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='assignee', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('critical', 'Critical'), ('major', 'Major'), ('medium', 'Medium'), ('minor', 'Minor'), ('trivial', 'Trivial')], default='trivial', max_length=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('fixed', 'Fixed'), ('fixed-v', 'Fixed (Verified)'), ('wont-fix-nr', "Won't Fix (Not reproducible)"), ('wont-fix-ib', "Won't Fix (Intended behavior)"), ('wont-fix-o', "Won't Fix (Obsolete)"), ('wont-fix-i', "Won't Fix (Infeasible)"), ('duplicate', 'Duplicate')], default='new', max_length=30),
        ),
        migrations.AddField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('bug', 'Bug'), ('feature-request', 'Feature Request'), ('customer-issue', 'Customer Issue'), ('internal-cleanup', 'Internal Cleanup'), ('process', 'Process'), ('vulnerability', 'Vulnerability')], default='bug', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.Ticket')),
            ],
        ),
    ]
