# Generated by Django 2.2.10 on 2021-03-12 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_historicalticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalticket',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('fixed', 'Fixed'), ('fixed (verified)', 'Fixed (Verified)'), ("won't fix (not reproducible)", "Won't Fix (Not reproducible)"), ("won't fix (intended behavior)", "Won't Fix (Intended behavior)"), ("won't fix (obsolete)", "Won't Fix (Obsolete)"), ("won't Fix (infeasible)", "Won't Fix (Infeasible)"), ('duplicate', 'Duplicate')], default='new', max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalticket',
            name='type',
            field=models.CharField(choices=[('bug', 'Bug'), ('feature request', 'Feature Request'), ('customer issue', 'Customer Issue'), ('internal cleanup', 'Internal Cleanup'), ('process', 'Process'), ('vulnerability', 'Vulnerability')], default='bug', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('fixed', 'Fixed'), ('fixed (verified)', 'Fixed (Verified)'), ("won't fix (not reproducible)", "Won't Fix (Not reproducible)"), ("won't fix (intended behavior)", "Won't Fix (Intended behavior)"), ("won't fix (obsolete)", "Won't Fix (Obsolete)"), ("won't Fix (infeasible)", "Won't Fix (Infeasible)"), ('duplicate', 'Duplicate')], default='new', max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('bug', 'Bug'), ('feature request', 'Feature Request'), ('customer issue', 'Customer Issue'), ('internal cleanup', 'Internal Cleanup'), ('process', 'Process'), ('vulnerability', 'Vulnerability')], default='bug', max_length=20),
        ),
    ]
