# Generated by Django 2.2.10 on 2021-03-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='image',
            field=models.ImageField(default=None, upload_to='attachment_pics'),
            preserve_default=False,
        ),
    ]
